### ISSUE TITLE
Bug - DelayedConfirmationViewDemo

### ISSUE THREAD

**Issue by kla4dj** [livefront/android-wear-demo#1]
I downloaded the Demo and tried all Demo Activities. Unfortunately the DelayedConfirmationView - Demo lets the App collapse. Looked through the code but could not find the issue.

**Comment by byencho** [comment]
Thanks for the update @kla4dj, I'll take a look and see what's going on! There have been some changes to the wearable support library recently so maybe there's some subtle change that has affected the `DelayedConfirmationView` demo.

**Comment by byencho** [comment]
@kla4dj The problem was due to a bug in `DelayedConfirmationView` in the latest version of the support library that causes a crash when setting the visibility to `GONE` in XML. A fix has been merged in from #2
