### ISSUE TITLE
Background image for watchface

### ISSUE THREAD

**Issue by kavehmb** [livefront/android-wear-demo#3]
How can I change the code in order to have some pre loaded background image shown on the active mode of watch face based on the current date/temp?

**Comment by weisers** [comment]
Hi! I'll provide some example code in the next week or so.

**Comment by weisers** [comment]
Hi! I'll provide some example code in the next week or so.

**Comment by weisers** [comment]
@kavehmb See commit https://github.com/livefront/android-wear-demo/commit/a1d7a9e22b187e019e95e4972829e9338962ab31 for an example on how to set a watch background.
